plugins {
    id 'fabric-loom' version '1.10.5'
    id 'maven-publish'
    id 'idea'
}

def targetProperties = new Properties()
file('gradle.properties').withInputStream { targetProperties.load(it) }
targetProperties.each { propertyName, propertyValue -> project.ext.set(propertyName, propertyValue) }

version = fabric_version
group = mod_group_id
base { archivesName = 'advancedarmordamagelimit-fabric-1.21.1' }
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings "net.fabricmc:yarn:${yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    compileOnly files(rootProject.file('libs/YiRanExpressionLib-1.0.0-universal.jar'))
}

loom {
    mixin {
        defaultRefmapName = 'advancedarmordamagelimit.refmap.json'
    }
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}

tasks.named('jar', Jar).configure {
    from {
        zipTree(rootProject.file('libs/YiRanExpressionLib-1.0.0-universal.jar'))
    } {
        exclude 'META-INF/**'
        exclude 'pack.mcmeta'
        exclude 'net/yiran/expressionlib/YiRanExpressionLib.class'
    }
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven { url = "file://${project.projectDir}/mcmodsrepo" }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('jar', Jar).configure {
    from(rootProject.file('LICENSE')) {
        into 'META-INF/licenses/advanced-armor-damage-limit'
    }
    from(rootProject.file('NOTICE.md')) {
        into 'META-INF'
    }
    from(rootProject.file('licenses/YiRanExpressionLib-LICENSE.txt')) {
        into 'META-INF/licenses/yiran-expression-lib'
    }
    from(rootProject.file('licenses/ArmorDamageLimit-MIT-LICENSE.txt')) {
        into 'META-INF/licenses/armor-damage-limit-original'
    }
}
