pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { name = 'Fabric'; url = 'https://maven.fabricmc.net/' }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'fabric-loom') {
                useModule("net.fabricmc:fabric-loom:${requested.version}")
            }
        }
    }
}

rootProject.name = 'AdvancedArmorDamageLimit-Fabric-1.21.1'
