plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.140'
    id 'idea'
}

version = mod_version
group = mod_group_id
base { archivesName = 'advanced-armor-damage-limit-neoforge-26.1.2' }
java.toolchain.languageVersion = JavaLanguageVersion.of(25)

repositories {
    ivy {
        url = rootProject.file('libs')
        patternLayout { artifact '[artifact].[ext]' }
        metadataSources { artifact() }
    }
}

neoForge {
    enable {
        version = neo_version
        disableRecompilation = true
    }
    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }
        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }
        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').absolutePath, '--existing', file('src/main/resources/').absolutePath
        }
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.java.srcDir rootProject.file('common/neoforge-26.1.2/src/main/java')

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    def expressionLib = implementation('com.github.yiran1457:YiRanExpressionLib:1.0.1') {
        artifact { name = 'YiRanExpressionLib-1.0.1-universal' }
    }
    jarJar(expressionLib) {
        version {
            strictly '[1.0.1]'
            prefer '1.0.1'
        }
    }
}
